#!/usr/bin/sh

cp .alias ~/
cp .environment ~/
cp .bashrc ~/
cp .helpers ~/
cp .emacs ~/
cp .radare2rc ~/
cp -r .config ~/
cp custom.map ~/
cp .gdbinit ~/
cp .tmux.conf ~/
cp .vimrc ~/
cp .Xdefaults ~/
cp .xinitrc ~/
cp .xmodmaprc ~/
cp .zshrc ~/
cp .xbindkeysrc.scm ~/
